import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function GET() {
  try {
    const projects = await prisma.project.findMany({
      include: {
        logs: {
          orderBy: [{ createdAt: "desc" }, { percentage: "desc" }],
          take: 1,
        },
      },
      orderBy: { createdAt: "desc" },
    });

    const projectsWithProgress = projects.map((project) => {
      const progress = project.logs[0]?.percentage || 0;
      // Ensure status is consistent with progress, handling existing data issues
      const status = progress === 100 ? "Done" : project.status;

      return {
        ...project,
        progress,
        status,
      };
    });

    return NextResponse.json(projectsWithProgress);
  } catch (error) {
    return NextResponse.json(
      { message: "Gagal mengambil data proyek" },
      { status: 500 },
    );
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { clientName, clientPhone, projectName, deadline } = body;

    if (!clientName || !clientPhone || !projectName || !deadline) {
      return NextResponse.json(
        { message: "Semua field wajib diisi" },
        { status: 400 },
      );
    }

    // Auto-format phone number if needed (basic normalization)
    let formattedPhone = clientPhone.replace(/\D/g, "");
    if (formattedPhone.startsWith("0")) {
      formattedPhone = "62" + formattedPhone.substring(1);
    }

    const project = await prisma.project.create({
      data: {
        clientName,
        clientPhone: formattedPhone,
        projectName,
        deadline: new Date(deadline),
        status: "On Progress",
        // uniqueToken is automatically generated by @default(cuid()) in schema
      },
    });

    return NextResponse.json(project, { status: 201 });
  } catch (error) {
    console.error("Create project error:", error);
    return NextResponse.json(
      { message: "Gagal membuat proyek baru" },
      { status: 500 },
    );
  }
}
